# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 906522e42ab3b30699f678c0288fa7a936ec3be59e02f9b9f0e9fb59595f3784f16f1b96769ad0c37606b36c13c512d5ac2d830ce2853714cc12c1b76a7e1c05

test:
  secret_key_base: 9341863ddf9145cc2893fafce396270aeb531d45bbdc5541211da7cc8dc0761059bd802fe6de229b5d4d8d06e89e557cceea16e709a863e1bb58a09a2606901b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
